package objectos;
// Generated 12 ene 2022 16:51:47 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * CalidadAireIndice generated by hbm2java
 */
public class CalidadAireIndice implements java.io.Serializable {

	private Integer id;
	private Estacion estacion;
	private Date fecha;
	private String hora;
	private Integer no2ica;
	private Integer noxgm3;
	private Integer pm10ica;
	private Integer pm25ica;
	private Integer so2ica;
	private String icaestacion;

	public CalidadAireIndice() {
	}

	public CalidadAireIndice(Estacion estacion, Date fecha) {
		this.estacion = estacion;
		this.fecha = fecha;
	}

	public CalidadAireIndice(Estacion estacion, Date fecha, String hora, Integer no2ica, Integer noxgm3,
			Integer pm10ica, Integer pm25ica, Integer so2ica, String icaestacion) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10ica = pm10ica;
		this.pm25ica = pm25ica;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public Integer getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(Integer no2ica) {
		this.no2ica = no2ica;
	}

	public Integer getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Integer noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public Integer getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(Integer pm10ica) {
		this.pm10ica = pm10ica;
	}

	public Integer getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(Integer pm25ica) {
		this.pm25ica = pm25ica;
	}

	public Integer getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(Integer so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
