package objectos;
// Generated 12 ene 2022 16:51:47 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * CalidadAireHorario generated by hbm2java
 */
public class CalidadAireHorario implements java.io.Serializable {

	private Integer id;
	private Estacion estacion;
	private Date fecha;
	private String hora;
	private Integer comgm3;
	private Integer nogm3;
	private Integer no2gm3;
	private Integer noxgm3;
	private Integer pm10gm3;
	private String pm25gm3;
	private String so2gm3;

	public CalidadAireHorario() {
	}

	public CalidadAireHorario(Estacion estacion, Date fecha, String hora) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
	}

	public CalidadAireHorario(Estacion estacion, Date fecha, String hora, Integer comgm3, Integer nogm3, Integer no2gm3,
			Integer noxgm3, Integer pm10gm3, String pm25gm3, String so2gm3) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
		this.comgm3 = comgm3;
		this.nogm3 = nogm3;
		this.no2gm3 = no2gm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public Integer getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(Integer comgm3) {
		this.comgm3 = comgm3;
	}

	public Integer getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(Integer nogm3) {
		this.nogm3 = nogm3;
	}

	public Integer getNo2gm3() {
		return this.no2gm3;
	}

	public void setNo2gm3(Integer no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public Integer getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Integer noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public Integer getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(Integer pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	public String getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(String pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	public String getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(String so2gm3) {
		this.so2gm3 = so2gm3;
	}

}
