package objetos;
// Generated 27 ene 2022 19:01:25 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * CalidadAireHorario generated by hbm2java
 */
public class CalidadAireHorario implements java.io.Serializable {

	private Integer id;
	private Estacion estacion;
	private Date fecha;
	private String hora;
	private String comgm3;
	private String nogm3;
	private String no2gm3;
	private String noxgm3;
	private String pm10gm3;
	private String pm25gm3;
	private String so2gm3;

	public CalidadAireHorario() {
	}

	public CalidadAireHorario(Estacion estacion, Date fecha, String hora) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
	}

	public CalidadAireHorario(Estacion estacion, Date fecha, String hora, String comgm3, String nogm3, String no2gm3,
			String noxgm3, String pm10gm3, String pm25gm3, String so2gm3) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
		this.comgm3 = comgm3;
		this.nogm3 = nogm3;
		this.no2gm3 = no2gm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(String comgm3) {
		this.comgm3 = comgm3;
	}

	public String getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(String nogm3) {
		this.nogm3 = nogm3;
	}

	public String getNo2gm3() {
		return this.no2gm3;
	}

	public void setNo2gm3(String no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public String getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(String noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public String getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(String pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	public String getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(String pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	public String getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(String so2gm3) {
		this.so2gm3 = so2gm3;
	}

}
