package objetos;
// Generated 14 ene 2022 15:45:44 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * CalidadAireIndice generated by hbm2java
 */
public class CalidadAireIndice implements java.io.Serializable {

	private Integer id;
	private Estacion estacion;
	private Date fecha;
	private String hora;
	private String no2ica;
	private String noxgm3;
	private String pm10ica;
	private String pm25ica;
	private String so2ica;
	private String icaestacion;

	public CalidadAireIndice() {
	}

	public CalidadAireIndice(Estacion estacion, Date fecha) {
		this.estacion = estacion;
		this.fecha = fecha;
	}

	public CalidadAireIndice(Estacion estacion, Date fecha, String hora, String no2ica, String noxgm3, String pm10ica,
			String pm25ica, String so2ica, String icaestacion) {
		this.estacion = estacion;
		this.fecha = fecha;
		this.hora = hora;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10ica = pm10ica;
		this.pm25ica = pm25ica;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public String getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(String noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
