package objetos;
// Generated 25 ene. 2022 17:35:55 by Hibernate Tools 5.5.7.Final

/**
 * Favoritos generated by hbm2java
 */
public class Favoritos implements java.io.Serializable {

	private Integer id;
	private EspaciosNaturales espaciosNaturales;
	private Municipio municipio;
	
	private Users users;

	public Favoritos() {
	}

	public Favoritos(EspaciosNaturales espaciosNaturales, Municipio municipio, Users users) {
		this.espaciosNaturales = espaciosNaturales;
		this.municipio = municipio;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
