package objetos;
// Generated 25 ene. 2022 11:12:30 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosId generated by hbm2java
 */
public class FavoritosId implements java.io.Serializable {

	private int idUser;
	private int idEspacioNatural;

	public FavoritosId() {
	}

	public FavoritosId(int idUser, int idEspacioNatural) {
		this.idUser = idUser;
		this.idEspacioNatural = idEspacioNatural;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdEspacioNatural() {
		return this.idEspacioNatural;
	}

	public void setIdEspacioNatural(int idEspacioNatural) {
		this.idEspacioNatural = idEspacioNatural;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosId))
			return false;
		FavoritosId castOther = (FavoritosId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdEspacioNatural() == castOther.getIdEspacioNatural());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdEspacioNatural();
		return result;
	}

}
