package objetos;
// Generated 25 ene. 2022 11:12:30 by Hibernate Tools 5.5.7.Final

/**
 * Favoritos generated by hbm2java
 */
public class Favoritos implements java.io.Serializable {

	private FavoritosId id;
	private EspaciosNaturales espaciosNaturales;
	private Users users;
	private Integer idMunicipio;

	public Favoritos() {
	}

	public Favoritos(FavoritosId id, EspaciosNaturales espaciosNaturales, Users users) {
		this.id = id;
		this.espaciosNaturales = espaciosNaturales;
		this.users = users;
	}

	public Favoritos(FavoritosId id, EspaciosNaturales espaciosNaturales, Users users, Integer idMunicipio) {
		this.id = id;
		this.espaciosNaturales = espaciosNaturales;
		this.users = users;
		this.idMunicipio = idMunicipio;
	}

	public FavoritosId getId() {
		return this.id;
	}

	public void setId(FavoritosId id) {
		this.id = id;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

}
