package objetos;
// Generated 20 ene 2022 18:01:55 by Hibernate Tools 5.5.7.Final

/**
 * Gallery generated by hbm2java
 */
public class Gallery implements java.io.Serializable {

	private Integer id;
	private Users users;
	private byte[] image;

	public Gallery() {
	}

	public Gallery(Users users, byte[] image) {
		this.users = users;
		this.image = image;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
