package objetos;
// Generated 27 ene 2022 19:01:25 by Hibernate Tools 5.5.7.Final

/**
 * Hash generated by hbm2java
 */
public class Hash implements java.io.Serializable {

	private int id;
	private String hash;

	public Hash() {
	}

	public Hash(int id) {
		this.id = id;
	}

	public Hash(int id, String hash) {
		this.id = id;
		this.hash = hash;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
