package objetos;
// Generated 13 ene 2022 17:50:37 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private String localidad;
	private String marca;
	private String territorio;
	private String tipo;
	private String territoryCode;
	private Set estacions = new HashSet(0);
	private Set espaciosNaturaleses = new HashSet(0);

	public Municipio() {
	}

	public Municipio(String nombre) {
		this.nombre = nombre;
	}

	public Municipio(String nombre, String descripcion, String localidad, String marca, String territorio, String tipo,
			String territoryCode, Set estacions, Set espaciosNaturaleses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.localidad = localidad;
		this.marca = marca;
		this.territorio = territorio;
		this.tipo = tipo;
		this.territoryCode = territoryCode;
		this.estacions = estacions;
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(String territorio) {
		this.territorio = territorio;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTerritoryCode() {
		return this.territoryCode;
	}

	public void setTerritoryCode(String territoryCode) {
		this.territoryCode = territoryCode;
	}

	public Set getEstacions() {
		return this.estacions;
	}

	public void setEstacions(Set estacions) {
		this.estacions = estacions;
	}

	public Set getEspaciosNaturaleses() {
		return this.espaciosNaturaleses;
	}

	public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

}
