package objetos;
// Generated 20 ene 2022 18:01:55 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private String userName;
	private String password;
	private Set galleries = new HashSet(0);

	public Users() {
	}

	public Users(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public Users(String userName, String password, Set galleries) {
		this.userName = userName;
		this.password = password;
		this.galleries = galleries;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getGalleries() {
		return this.galleries;
	}

	public void setGalleries(Set galleries) {
		this.galleries = galleries;
	}

}
