package objetos;
// Generated 25 ene. 2022 17:35:55 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private String userName;
	private String password;
	private Set favoritoses = new HashSet(0);

	public Users() {
	}

	public Users(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public Users(String userName, String password, Set favoritoses) {
		this.userName = userName;
		this.password = password;
		this.favoritoses = favoritoses;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getFavoritoses() {
		return this.favoritoses;
	}

	public void setFavoritoses(Set favoritoses) {
		this.favoritoses = favoritoses;
	}

}
