package objetos;
// Generated 22 ene. 2022 21:44:56 by Hibernate Tools 5.5.7.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private String userName;
	private String password;

	public Users() {
	}

	public Users(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
